# Generated by Django 3.0.6 on 2020-05-29 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, null=True)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('length_min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('no_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.CharField(max_length=1)),
                ('seat_number', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_site.Rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Screenings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_site.Films')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_site.Rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Reserved_seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_site.Bookings')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_site.Seats')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_site.Customers'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_site.Screenings'),
        ),
    ]
