# Generated by Django 3.0.6 on 2020-05-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_site', '0002_auto_20200530_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
